# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(max_length=20)),
                ('urlType', models.CharField(max_length=5)),
                ('urlResponse', models.CharField(max_length=1000)),
                ('urldate', models.DateField(max_length=20)),
            ],
        ),
    ]
