# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockdata',
            name='urldate',
        ),
    ]
