# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockapi', '0002_remove_mockdata_urldate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockdata',
            old_name='urlname',
            new_name='urlName',
        ),
    ]
